### ISSUE TITLE
ספרינט 1 - משימות טומי

### ISSUE THREAD

**Issue by tommygoX** [droru/wushu-server#25]
Tommy:
ברשימת מועדונים – להוסיף שדות שם עמותה ומספר עמותה-
ברישום ספורטאים להחליף את שם השדה לכתובת יישוב ולאפשר לסמן: טלאו/ סנדא/ גם וגם-
ברשימת ספורטאים להוסיף סינון לפי טלאו/סנדא.-
לשנות כיתוב ברישום מאמנים לרישום מאמן/מדריך-

**Comment by wushu-SYS** [comment]
close
