### ISSUE TITLE
ספרינט 2 נטע- במסך רשימת ספורטאים להוסיף את השדות: שנת לידה, שם מאמן, תוקף בדיקה רפואית ועיר

### ISSUE THREAD

**Issue by netas34** [droru/wushu-server#26]

**Comment by netas34** [comment]
תוקף בדיקות רפואיות זה קצת בעייתי. לא קיים רשומה כזאת במערכת.
לאחר שיחה עם רמי כרגע אין צורך לגעת בכל הקשור לייצוא לאקסל.

**Comment by wushu-SYS** [comment]
אני מתקשה לייבא את השדות. לא מצליחה להציג אותם בטבלה באתר
